name: 'MechanicsCore'
author: 'DeeCaaD'
authors:
  - 'CJCrafter'
version: '1.0.0'
api-version: '1.13' # DO NOT SET HIGHER OR LOWER THAN THIS
description: 'Useful tools for plugins to use.'
main: 'me.deecaad.core.MechanicsCore'
softdepend:
  - 'PlaceholderAPI'