# me.deecaad.weaponmechanics.weapon.projectile.ProjectileSettings
Projectile_Settings:
  Type: <ProjectileType>
  Projectile_Item_Or_Block:
    Type: <Material>:<Data>
    Durability: <durability>
    Unbreakable: <true/false>
    Custom_Model_Data: <custom model data number>
    Skull:
      Owning_Player: <UUID of player or name of player>
    Potion:
      Color: <ColorType>
  Gravity: <gravity>
  Minimum:
    Speed: <minimum speed of projectile>
    Remove_Projectile_On_Speed_Reached: <true/false>
  Maximum:
    Speed: <maximum speed of projectile>
    Remove_Projectile_On_Speed_Reached: <true/false>
  Decrease_Motion:
    Base: <multiplier>
    In_Water: <multiplier>
    When_Raining_Or_Snowing: <multiplier>
  Disable_Entity_Collisions: <true/false>
  Maximum_Alive_Ticks: <ticks>
  Maximum_Travel_Distance: <distance>
  Size: <projectile size>