# the debug level dictates what is printed to console
#   0: No printing
#   1: Errors/Info
#   2: Warnings (Suggested)
#   3: Debug
Debug_Level: 2
Print_Traces: false

# The MechanicsCore item registry is *very* primitive. Imagine you have 'steel'
# and 'steel_sheet' as 2 custom items. When MechanicsCore first loads,
# 'steel_sheet' will actually be broken since 'steel' doesn't exist yet. To fix
# this, we loop a few times until no errors occur. If you have a *highly
# complex* crafting system, then you may want to raise this number. You should
# never need to lower it.
Item_Loop_Limit: 10

# When a mistake is found in config, how many options do we print?
# Bigger numbers = more information
# Smaller numbers = tidier console
Show_Serialize_Options: 32

# If you don't use a specific trigger, it can be disabled here. The performance
# boost is minor, but it's here if you need it.
Disabled_Trigger_Checks:
  In_Midair: false
  Standing_And_Walking: false
  Jump: false
  Double_Jump: true # Disabled by default since this allows players to do slight double jump and go over 2 blocks
  Swim: false
  Glide: false
  Sneak: false
  Sprint: false
  Right_And_Left_Click: false
  Drop_Item: false
  Swap_Hand_Items: false